name: ubuntu-2004-builder container

env:
  GITHUB_OUTPUT: ""

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/ubuntu-2004-builder.yml"
      - "supervisord.conf"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
    paths:
      - "Dockerfile"
      - ".github/workflows/ubuntu-2004-builder.yml"
      - "supervisord.conf"

jobs:
  ubuntu-2004-builder:
    name: psibase-ubuntu-2004-builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/psinode-ubuntu-2004"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:latest"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT
      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          pull: true
          file: Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
